name: "Bookshelf Action: Issue Comment"
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  issues: write
jobs:
  bookshelf-action:
    name: Bookshelf Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - name: Run Bookshelf Action
        uses: AnandChowdhary/bookshelf-action@HEAD
        with:
          command: "onIssueComment"
        env:
          GITHUB_TOKEN: ${{ github.token }}
