name: "Bookshelf Action: New Issue"
on:
  issues:
    types: [opened]
jobs:
  bookshelf-action:
    name: Bookshelf Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Bookshelf Action
        uses: AnandChowdhary/bookshelf-action@HEAD
        with:
          command: "onNewIssue"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delay for 10 seconds
        if: github.repository == 'AnandChowdhary/books'
        run: sleep 10
      - name: Dispatch AnandChowdhary/everything update
        if: github.repository == 'AnandChowdhary/books'
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          repo: AnandChowdhary/everything
          workflow: api.yml
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
